version: '3'

services:
  rp:
    build: ./rp
    ports:
      - "3000:3000"
    depends_on:
      - idp
      
  idp:
    build: ./idp
    ports:
      - "3001:3001"
    environment:
      - ATTACKER_URL=https://8b8a4f6763b5907a2949f3a21e277bbc.m.pipedream.net
